version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.3.4-node-browsers
         environment:
           RAILS_ENV: test
           PGHOST: 127.0.0.1
           DATABASE_URL: postgres://bike_incident@127.0.0.1/bike_incident_test
       - image: circleci/postgres:9.6
         environment:
           POSTGRES_USER: bike_incident
           POSTGRES_DB: bike_incident_test
           POSTGRES_PASSWORD: ""

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:migrate

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            bundle exec rspec

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
