default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bike_incident_dev

test:
  <<: *default
  host: localhost
  database: bike_incident_test

production:
  <<: *default
  database: bike_incident_prod
  url: <%= ENV['DATABASE_URL'] %>
